#!/usr/bin/env bun
// Reads dist/bundle.js and writes dist/bundle-module.ts, which exports the
// bundle content as a base64 string. This lets `bun build --compile` bundle
// the client JS directly into the binary without relying on file embedding.
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const root = join(import.meta.dir, "..");
const bundle = readFileSync(join(root, "dist/bundle.js"), "utf-8");
const b64 = Buffer.from(bundle).toString("base64");

mkdirSync(join(root, "dist"), { recursive: true });
writeFileSync(
  join(root, "dist/bundle-module.ts"),
  `// Auto-generated by scripts/generate-bundle-module.ts — do not edit.\n// Run \`bun run build\` to regenerate.\nexport const CLIENT_BUNDLE_B64 = "${b64}";\n`
);
console.log("Generated dist/bundle-module.ts");
